### ISSUE TITLE
Error loading images and videos 

### ISSUE THREAD

**Issue by aldo-canedo** [pierdr/Tramontana-for-Processing#1]
hi @pierdr amazing library, sadly i am not able to load multimedia resources in android via web, im trying modifying the ChangeColor example with an image from my webpage.

void mousePressed(){
 if(mouseX<width/2 && mouseY<height/2)
 {
   //t.setColor(255,128,128,255);
   t.showImage("http://fragments.com.mx/img/entradas/e_prelude/7.png");
 }

i even try loading the image via local with a python server 

void mousePressed(){
 if(mouseX<width/2 && mouseY<height/2)
 {
   //t.setColor(255,128,128,255);
   t.showImage("http://127.0.0.1:8000/descarga.png");
 }

Do you think than im doing something wrong or its something else ?

**Comment by egueli** [comment]
Hi Aldo,
thanks for your report. it looks that the app is currently able to handle `https` addresses, but not `http` ones.
I'll push an update to the app soon, then I'll close this bug.

**Comment by egueli** [comment]
Hi @aldo-canedo I released version 1.2.2 of the Android app: it has the fix for this bug. Please update it on your phone and let me know if you still have issues. Cheers!
